<?php
//COMMON
require_once $system_path.'core/Model.php';

//SUB SYSTEM
require_once APPPATH.'models/biz/BaseBiz.php';
require_once APPPATH.'models/biz/AdminAccountBiz.php';
require_once APPPATH.'models/biz/BizUser.php';
require_once APPPATH.'models/biz/BizSeller.php';


//portal

require_once APPPATH.'models/biz/PortalBizBase.php';
require_once APPPATH.'models/biz/PortalBizAccount.php';
require_once APPPATH.'models/biz/PortalBizPassword.php';
require_once APPPATH.'models/biz/PortalBizPayment.php';
require_once APPPATH.'models/biz/PortalBizUserHistory.php';
require_once APPPATH.'models/biz/PortalBizPaymentHistory.php';
require_once APPPATH.'models/biz/PortalBizContact.php';
require_once APPPATH.'models/biz/PortalBizLanguage.php';
require_once APPPATH.'models/biz/PortalBizInvoice.php';
require_once APPPATH.'models/biz/PortalBizOrder.php';






