<?php
//COMMON
require_once $system_path.'core/Model.php';

//SUB SYSTEM
require_once APPPATH.'models/BizService/BaseBiz.php';
require_once APPPATH.'models/BizService/AdminAccountBiz.php';
require_once APPPATH.'models/BizService/BizUser.php';
require_once APPPATH.'models/BizService/BizSeller.php';


//portal
require_once APPPATH.'models/BizService/SerivceFactory.php';
require_once APPPATH.'models/BizService/PortalBizBase.php';
require_once APPPATH.'models/BizService/PortalBizAccount.php';
require_once APPPATH.'models/BizService/PortalBizPassword.php';
require_once APPPATH.'models/BizService/PortalBizPayment.php';
require_once APPPATH.'models/BizService/PortalBizUserHistory.php';
require_once APPPATH.'models/BizService/PortalBizPaymentHistory.php';
require_once APPPATH.'models/BizService/PortalBizContact.php';
require_once APPPATH.'models/BizService/PortalBizLanguage.php';
require_once APPPATH.'models/BizService/PortalBizInvoice.php';
require_once APPPATH.'models/BizService/PortalBizOrder.php';






