<?php
//COMMON
require_once $system_path.'core/Model.php';

//SUB SYSTEM
require_once APPPATH.'models/biz/BaseBiz.php';
require_once APPPATH.'models/biz/AdminAccountBiz.php';

//portal
require_once APPPATH.'models/biz/PortalBaseBiz.php';
require_once APPPATH.'models/biz/PortalAccountBiz.php';
require_once APPPATH.'models/biz/PortalLoginBiz.php';
require_once APPPATH.'models/biz/PortalUserHistoryBiz.php';
require_once APPPATH.'models/biz/PortalPassowordBiz.php';



