<?php
//COMMON
require_once $system_path.'core/Model.php';
//SUB SYSTEM
require_once APPPATH.'models/Repository/BaseModel.php';
// require_once APPPATH.'models/Repository/AdminAccountModel.php';
// require_once APPPATH.'models/Repository/SellerModel.php';
// require_once APPPATH.'models/Repository/UserModel.php';
// require_once APPPATH.'models/Repository/FileModel.php';

//portal
require_once APPPATH.'models/Repository/_RepositoryConst.php';
require_once APPPATH.'models/Repository/PortalModelBase.php';
require_once APPPATH.'models/Repository/PortalModelCommon.php';
require_once APPPATH.'models/Repository/PortalModelInvoice.php';
require_once APPPATH.'models/Repository/PortalModelInvoiceOtherCost.php';
require_once APPPATH.'models/Repository/PortalModelInvoiceProduct.php';
require_once APPPATH.'models/Repository/PortalModelInvoiceShipping.php';
require_once APPPATH.'models/Repository/PortalModelLogin.php';
require_once APPPATH.'models/Repository/PortalModelOrder.php';
require_once APPPATH.'models/Repository/PortalModelPaymentTemp.php';
require_once APPPATH.'models/Repository/PortalModelProduct.php';
require_once APPPATH.'models/Repository/PortalModelTax.php';
require_once APPPATH.'models/Repository/PortalModelUser.php';
require_once APPPATH.'models/Repository/PortalModelUserContact.php';
require_once APPPATH.'models/Repository/PortalModelUserHistory.php';
require_once APPPATH.'models/Repository/PortalModelUserSetting.php';
require_once APPPATH.'models/Repository/PortalModelOrderStatus.php';
require_once APPPATH.'models/Repository/PortalModelNLPayment.php';










