<?php
require_once APPPATH.'libraries/nusoap/class.nusoap_base.php';
require_once APPPATH.'libraries/nusoap/class.soap_fault.php';
require_once APPPATH.'libraries/nusoap/class.soap_parser.php';
require_once APPPATH.'libraries/nusoap/class.soap_server.php';
require_once APPPATH.'libraries/nusoap/class.soap_transport_http.php';
require_once APPPATH.'libraries/nusoap/class.soap_val.php';
require_once APPPATH.'libraries/nusoap/class.soapclient.php';
require_once APPPATH.'libraries/nusoap/class.wsdl.php';
require_once APPPATH.'libraries/nusoap/class.wsdlcache.php';
require_once APPPATH.'libraries/nusoap/class.xmlschema.php';
require_once APPPATH.'libraries/nusoap/nusoap.php';
require_once APPPATH.'libraries/nusoap/nusoapmime.php';
