  ALTER TABLE `t_order_status`
  CHANGE `status` `status` ENUM('VERIFYING','SHIPPING','DELIVERED','ORDER_PLACED','ORDER_CANCELLED','REJECTED','FAIL_TO_DELIVER') CHARSET utf8 COLLATE utf8_unicode_ci NULL;
