<?php
require_once APPPATH.'models/PaymentService/PortalPaymentOnepay.php';
require_once APPPATH.'models/PaymentService/PortalPaymentManager.php';
require_once APPPATH.'models/PaymentService/PortalPaymentNganLuong.php';
require_once APPPATH.'models/PaymentService/PortalPaymentStrategy.php';
require_once APPPATH.'models/PaymentService/PortalPaymentVisaAndMaster.php';

require_once APPPATH.'models/PaymentService/rate/rate.inc';